import React from 'react'
import Calltoexpert from '../../../Components/Calltoexpert'

const page = () => {
  return (
    <div>
      <div className="flex justify-center text-center items-center bg-[url(/solar.jpg)]  bg-cover bg-center h-64 ">
        <h1 className='text-6xl font-extrabold text-[#082E6F] '>SOLAR STREET LIGHTS</h1>
      </div>

      <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8'>
        <h1 className='text-center text-3xl font-bold text-gray-800 mb-8 border-l-[5px] border-r-[5px] border-gray-800'>SOLAR STREET LIGHTS IN PAKISTAN</h1>
        <p>In Pakistan, street lights commonly prevail to provide a sense of security for homes, towns, and markets. However, a couple of hours of load shedding during the night and continuously rising electricity prices make it quite challenging for homeowners, town residents, and market owners to keep the lights on for better security purposes during the night. In such circumstances, renewable energy, particularly solar energy, emerges as the best problem solver. With solar lights, energy is saved during the day and automatically activated as the sun sets. </p>
      </div>

      <Calltoexpert />

      <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8'>
  <div className="flex flex-col md:flex-row gap-6">
    {/* Left Side - Text Content Divs */}
    <div className="md:w-1/2 flex flex-col gap-6">
      {/* First Nested Div */}
      <div className="bg-white p-6 rounded-xl shadow-md">
        <h3 className="text-xl font-bold text-gray-800 mb-3">What are Solar Street Lights?</h3>
        <p className="text-gray-600">
          Solar street lights in Pakistan are just like normal outdoor lighting systems, but they use solar panels to harness sunlight and convert it into electrical energy. This energy is stored in batteries during the day. In most cases, the street light contains built-in batteries and a sensor system. When the sunlight dims, they automatically turn on and are powered by this stored energy during the night.
        </p>
      </div>

      {/* Second Nested Div */}
      <div className="bg-white p-6 rounded-xl shadow-md">
        <h3 className="text-xl font-bold text-gray-800 mb-3">How Solar Street Lights Work?</h3>
        <p className="text-gray-600">
          Solar LED street lights are commonly installed on poles, with solar panels positioned at the top. These panels absorb sunlight and turn solar energy into electricity. The built-in charge controller and batteries then transform the DC electricity into AC light and batteries store the electricity for illuminating the lights at night. When the sun sets and it gets dark, the solar LED street lights automatically recognize the evening time and turn on.
        </p>
      </div>
    </div>

    {/* Right Side - Image Div */}
    <div className="md:w-1/2">
      <img
        src="/solar-street-light.jpg"  // Changed to more relevant image
        alt="Solar Street Light"
        className="w-full h-full rounded-xl shadow-lg object-cover"
      />
    </div>
  </div>
</div>

      <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8'>
        <div className="max-w-6xl mx-auto p-4 sm:p-6 bg-white rounded-xl shadow-md">
          <h2 className="text-2xl md:text-3xl font-bold text-gray-800 mb-6 text-center">
            How Solar Street Lights Work: Key Components & Process
          </h2>

          <div className="overflow-x-auto">
            <table className="w-full border-collapse">
              <thead>
                <tr className="bg-[#5AA86C] text-white">
                  <th className="p-3 sm:p-4 text-left rounded-tl-xl">Component</th>
                  <th className="p-3 sm:p-4 text-center">Function</th>
                  <th className="p-3 sm:p-4 text-right rounded-tr-xl">Working Principle</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {/* Solar Panel */}
                <tr className="hover:bg-gray-50">
                  <td className="p-3 sm:p-4 font-medium">Solar Panel</td>
                  <td className="p-3 sm:p-4 text-center text-gray-600">Energy Collection</td>
                  <td className="p-3 sm:p-4 text-right text-gray-600">
                    Converts sunlight into DC electricity via photovoltaic cells during daylight.
                  </td>
                </tr>

                {/* Battery */}
                <tr className="hover:bg-gray-50 bg-gray-50/50">
                  <td className="p-3 sm:p-4 font-medium">Battery (Lithium-ion/LED)</td>
                  <td className="p-3 sm:p-4 text-center text-gray-600">Energy Storage</td>
                  <td className="p-3 sm:p-4 text-right text-gray-600">
                    Stores excess energy generated by the solar panel for nighttime use.
                  </td>
                </tr>

                {/* LED Light */}
                <tr className="hover:bg-gray-50">
                  <td className="p-3 sm:p-4 font-medium">LED Light Fixture</td>
                  <td className="p-3 sm:p-4 text-center text-gray-600">Illumination</td>
                  <td className="p-3 sm:p-4 text-right text-gray-600">
                    Uses stored energy to provide bright, efficient lighting (auto-activated at dusk).
                  </td>
                </tr>

                {/* Charge Controller */}
                <tr className="hover:bg-gray-50 bg-gray-50/50">
                  <td className="p-3 sm:p-4 font-medium">Charge Controller</td>
                  <td className="p-3 sm:p-4 text-center text-gray-600">Power Regulation</td>
                  <td className="p-3 sm:p-4 text-right text-gray-600">
                    Prevents overcharging/discharging, extending battery life.
                  </td>
                </tr>

                {/* Pole & Sensors */}
                <tr className="hover:bg-gray-50">
                  <td className="p-3 sm:p-4 font-medium">Pole & Motion Sensors</td>
                  <td className="p-3 sm:p-4 text-center text-gray-600">Support & Automation</td>
                  <td className="p-3 sm:p-4 text-right text-gray-600">
                    Adjusts brightness based on movement (optional feature).
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className="mt-6 flex justify-center">
            <button className="bg-[#5AA86C] hover:bg-[#4a8a5a] text-white font-medium py-2 px-6 rounded-lg transition hover:scale-105">
              Get Quote
            </button>
          </div>
        </div>
      </div>

    </div>
  )
}

export default page
