import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdminRouteChecker from '../app/AdminRouteChecker'
import { ThemeProvider } from '../context/ThemeContext'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "GO GREEN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>

        <link sizes="192x192" rel="icon" type="image/png" href="/companylogo.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider>
          <AdminRouteChecker>
            {children}
          </AdminRouteChecker>
        </ThemeProvider>

      </body>
    </html>
  );
}
